{"timestamp": "2025-07-11T01:12:52.240863", "context": "core_character_cards", "action": "error_occurred", "data": {"exception": "[Errno 2] No such file or directory: 'sword_weirdos/data/characters/karra.json'"}, "state": {"traceback": "Traceback (most recent call last):\n  File \"D:\\Docs\\Python\\BridgeRPProject\\sword_weirdos\\core\\character_cards.py\", line 16, in load_character\n    with open(file_path, \"r\") as f:\n         ~~~~^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'sword_weirdos/data/characters/karra.json'\n"}, "ai_tags": ["system", "char_data", "runtime_behavior", "init"], "trace_id": "c62c85de-ff37-4f3d-a6ab-e517745049e8"}
{"timestamp": "2025-07-11T01:41:20.831343", "context": "core_character_cards", "action": "error_occurred", "data": {"exception": "[Errno 2] No such file or directory: 'sword_weirdos/data/characters/karra.json'"}, "state": {"traceback": "Traceback (most recent call last):\n  File \"D:\\Docs\\Python\\BridgeRPProject\\sword_weirdos\\core\\character_cards.py\", line 52, in save_character\n    trace_id = generate_trace_id()\n             ^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'sword_weirdos/data/characters/karra.json'\n"}, "ai_tags": ["system", "char_data", "runtime_behavior", "input"], "trace_id": "5f7e6a52-ffc3-4508-89fa-a2c06ce18ed8"}
